/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package coloniahormigas;

import java.awt.Button;
import java.awt.TextArea;
import javafx.scene.Scene;
import javafx.scene.control.Label;
import javafx.scene.control.ToolBar;
import javafx.scene.layout.BorderPane;
import javafx.stage.Stage;

/**
 *
 * @author Karen
 */
public class Colonias extends javax.swing.JPanel {

    /**
     * Creates new form Colonias
     */
    final int[][] COORDENADAS = {{0, 0}, {1, 0}, {2, 0}, {3, 0}, {4, 0}, {5, 0}, {6, 0}, {7, 0}, {8, 0}, {9, 0}, {10, 0}, {11, 0}};

    private Button btnInicializar;
    private Button btnEjecutar;
    private TextArea list;
    private Colonia colonia;
    public Colonias() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_ejecutar = new javax.swing.JButton();

        btn_ejecutar.setText("jButton1");
        btn_ejecutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ejecutarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(437, Short.MAX_VALUE)
                .addComponent(btn_ejecutar)
                .addGap(168, 168, 168))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(btn_ejecutar)
                .addContainerGap(370, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ejecutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ejecutarActionPerformed
        execute();
    }//GEN-LAST:event_btn_ejecutarActionPerformed

 public void execute() {
        Hormiga mejor = colonia.buscarSolucion(1000);
        list.setText(list.getText() + colonia.getProceso() + "Mejor Hormiga Final: " + mejor.aString() + "  Aptitud: " +mejor.getAptitud() + "\n");
    }
 public void start(Stage stage) throws Execption {
        stage.setTitle("Algoritmo \"Colonia de Hormigas\" - Hola Mundo");
        stage.setResizable(false);

        BorderPane bp = new BorderPane();
        ToolBar tb = new ToolBar();

        btnInicializar = new Button("Inicializar");
        btnInicializar.setOnAction(e -> {
            begin();
        });

        btnEjecutar = new Button("Ejecutar");
        btnEjecutar.setOnAction(e -> {
            execute();
        });

        tb.getItems().addAll( new Label("Genetico: "), btnInicializar, btnEjecutar);
        list = new TextArea();
        list.setEditable(false);
        bp.setTop(tb);
        bp.setCenter(list);

        Scene scene = new Scene(bp);
        stage.setScene(scene);
        stage.show();
    }

    public void begin() {
        //list.clear();
        colonia = new Colonia(COORDENADAS.length, COORDENADAS, 12, 0.1);
        list.setText("Mejor Hormiga Inicial: " + colonia.getMejor().aString() + "  Aptitud: " +colonia.getMejor().getAptitud() + "\n");
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ejecutar;
    // End of variables declaration//GEN-END:variables
}
