/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package coloniahormigas;

import java.awt.Button;
import java.awt.TextArea;
import javafx.scene.Scene;
import javafx.scene.control.ToolBar;
import javafx.scene.layout.BorderPane;
import javafx.stage.Stage;
import javax.swing.DefaultListModel;

/**
 *
 * @author Karen
 */
public class Visual extends javax.swing.JFrame {

    /**
     * Creates new form Visual
     */
    final int[][] COORDENADAS = {{0, 0}, {1, 0}, {2, 0}, {3, 0}, {4, 0}, {5, 0}, {6, 0}, {7, 0}, {8, 0}, {9, 0}, {10, 0}, {11, 0}};

    private Button btnInicializar;
    private Button btnEjecutar;
    private TextArea list;
    private Colonia colonia;
    DefaultListModel<String> model = new DefaultListModel<>();
    public Visual() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_ejecutar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lbx_r = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_ejecutar.setText("Ejecutar");
        btn_ejecutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ejecutarActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(lbx_r);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(217, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btn_ejecutar, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(125, Short.MAX_VALUE)
                .addComponent(btn_ejecutar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ejecutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ejecutarActionPerformed
        begin();
        execute();
    }//GEN-LAST:event_btn_ejecutarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Visual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Visual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Visual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Visual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Visual().setVisible(true);
            }
        });
    }
public void execute() {
        Hormiga mejor = colonia.buscarSolucion(1000);
        
        //((DefaultListModel)lbx_r.getModel()).addElement(list.getText() + colonia.getProceso() + "Mejor Hormiga Final: " + mejor.aString() + "  Aptitud: " +mejor.getAptitud() + "\n");
        model.addElement( "\n"+colonia.getProceso() + "Mejor Hormiga Final: " + mejor.aString() + "  Aptitud: " +mejor.getAptitud() + "\n");
        lbx_r.setModel(model);
    }
 public void start(Stage stage) {
        stage.setTitle("Algoritmo \"Colonia de Hormigas\" - Hola Mundo");
        stage.setResizable(false);

        BorderPane bp = new BorderPane();
        ToolBar tb = new ToolBar();

        btnInicializar = new Button("Inicializar");
       

        btnEjecutar = new Button("Ejecutar");

        Scene scene = new Scene(bp);
        stage.setScene(scene);
        stage.show();
    }

    public void begin() {
        //list.clear();
        colonia = new Colonia(COORDENADAS.length, COORDENADAS, 12, 0.1);
        //((DefaultListModel)lbx_r.getModel()).addElement("Mejor Hormiga Inicial: " + colonia.getMejor().aString() + "  Aptitud: " +colonia.getMejor().getAptitud() + "\n");
        model.addElement("Mejor Hormiga Inicial: " + colonia.getMejor().aString() + "  Aptitud: " +colonia.getMejor().getAptitud() + "\n");
        lbx_r.setModel(model);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ejecutar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> lbx_r;
    // End of variables declaration//GEN-END:variables
}
